// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: telegram-calendar-examples/standalone_service/telegram_calendar.proto

package telegram_calendar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CalendarService_GenerateCalendar_FullMethodName = "/telegram.calendar.CalendarService/GenerateCalendar"
	CalendarService_GetSettings_FullMethodName      = "/telegram.calendar.CalendarService/GetSettings"
	CalendarService_ApplyNewSettings_FullMethodName = "/telegram.calendar.CalendarService/ApplyNewSettings"
)

// CalendarServiceClient is the client API for CalendarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalendarServiceClient interface {
	GenerateCalendar(ctx context.Context, in *GenerateCalendarRequest, opts ...grpc.CallOption) (*GenerateCalendarResponse, error)
	GetSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSettingsResponse, error)
	ApplyNewSettings(ctx context.Context, in *NewSettingsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type calendarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarServiceClient(cc grpc.ClientConnInterface) CalendarServiceClient {
	return &calendarServiceClient{cc}
}

func (c *calendarServiceClient) GenerateCalendar(ctx context.Context, in *GenerateCalendarRequest, opts ...grpc.CallOption) (*GenerateCalendarResponse, error) {
	out := new(GenerateCalendarResponse)
	err := c.cc.Invoke(ctx, CalendarService_GenerateCalendar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) GetSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSettingsResponse, error) {
	out := new(GetSettingsResponse)
	err := c.cc.Invoke(ctx, CalendarService_GetSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ApplyNewSettings(ctx context.Context, in *NewSettingsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CalendarService_ApplyNewSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServiceServer is the server API for CalendarService service.
// All implementations must embed UnimplementedCalendarServiceServer
// for forward compatibility
type CalendarServiceServer interface {
	GenerateCalendar(context.Context, *GenerateCalendarRequest) (*GenerateCalendarResponse, error)
	GetSettings(context.Context, *emptypb.Empty) (*GetSettingsResponse, error)
	ApplyNewSettings(context.Context, *NewSettingsRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCalendarServiceServer()
}

// UnimplementedCalendarServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalendarServiceServer struct {
}

func (UnimplementedCalendarServiceServer) GenerateCalendar(context.Context, *GenerateCalendarRequest) (*GenerateCalendarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCalendar not implemented")
}
func (UnimplementedCalendarServiceServer) GetSettings(context.Context, *emptypb.Empty) (*GetSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedCalendarServiceServer) ApplyNewSettings(context.Context, *NewSettingsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyNewSettings not implemented")
}
func (UnimplementedCalendarServiceServer) mustEmbedUnimplementedCalendarServiceServer() {}

// UnsafeCalendarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalendarServiceServer will
// result in compilation errors.
type UnsafeCalendarServiceServer interface {
	mustEmbedUnimplementedCalendarServiceServer()
}

func RegisterCalendarServiceServer(s grpc.ServiceRegistrar, srv CalendarServiceServer) {
	s.RegisterService(&CalendarService_ServiceDesc, srv)
}

func _CalendarService_GenerateCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).GenerateCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalendarService_GenerateCalendar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).GenerateCalendar(ctx, req.(*GenerateCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalendarService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).GetSettings(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ApplyNewSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ApplyNewSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalendarService_ApplyNewSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ApplyNewSettings(ctx, req.(*NewSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalendarService_ServiceDesc is the grpc.ServiceDesc for CalendarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalendarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telegram.calendar.CalendarService",
	HandlerType: (*CalendarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCalendar",
			Handler:    _CalendarService_GenerateCalendar_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _CalendarService_GetSettings_Handler,
		},
		{
			MethodName: "ApplyNewSettings",
			Handler:    _CalendarService_ApplyNewSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telegram-calendar-examples/standalone_service/telegram_calendar.proto",
}
